name: odata-reusable-build-and-test

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      distribution:
        required: true
        type: string
      maven-options:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build CAP bookshop test image
        run: |
          docker build -t camunda/sap-odata-connector/cap-bookshop odata-connector/cap-bookshop

      - name: set up jdk ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: maven

#      - name: test env var availability
#        env:
#          destinations: ${{ secrets.DESTINATIONS }}
#        run: echo $destinations

      - name: build and test with maven
        env:
          destinations: ${{ secrets.DESTINATIONS }}
        working-directory: odata-connector
        run: mvn -B ${{ inputs.maven-options }} --file pom.xml
