name: rfc-reusable-build-and-test

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      distribution:
        required: true
        type: string
      maven-options:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up jdk ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: maven

      # second, prep deployment descriptor
      - name: download mtad.yaml
        uses: actions/download-artifact@v5
        with:
          name: client-config
          path: .

      # this runs w/ the deployed (!) connector
      # against c8 saas
      # and ecc
      - name: e2e tests (deployed connector, against c8 + ecc)
        env:
          e2e: true
        run: |
          # by env var e2e, only the respective tests are run
          export CLIENT_ID=$(jq -r .clientId values.json)
          export CLIENT_SECRET=$(jq -r .clientSecret values.json)
          export GRPC_ADDRESS=$(jq -r .grpcAddress values.json)
          export REST_ADDRESS=$(jq -r .restAddress values.json)
          mvn -pl rfc-connector ${{ inputs.maven-options }} test
