name: rfc-unit-test

on:
  pull_request:
    branches: [ "release/*", "main" ]
  push:
    branches: [ "release/*", "main" ]

jobs:
  build-and-test:
    uses: ./.github/workflows/rfc-reusable-unit-test.yml
    with:
      java-version: '21'
      distribution: 'temurin'
      maven-options: '-PcheckFormat'
