name: Automerge Release-Please PRs

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Import Secrets
      id: vault-secrets
      uses: hashicorp/vault-action@v3.0.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID}}
        secrets: |
          secret/data/common/gha BACKPORT_APP_ID;
          secret/data/common/gha BACKPORT_APP_KEY;
    - name: Generate a GitHub token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ steps.vault-secrets.outputs.BACKPORT_APP_ID }}
        private-key: ${{ steps.vault-secrets.outputs.BACKPORT_APP_KEY }}
